// ============================================================
// NGÂN HÀNG CÂU HỎI - 200 CÂU - ĐOÀN TNCS HỒ CHÍ MINH
// Cấu trúc: { text, options[4], correct (index 0-3) }
// ============================================================
const QUESTION_BANK = [
  // === LỊCH SỬ ĐOÀN (1-30) ===
  { text: "Đoàn Thanh niên Cộng sản Hồ Chí Minh được thành lập vào ngày tháng năm nào?", options: ["26/3/1930","19/5/1941","02/9/1945","03/2/1930"], correct: 0 },
  { text: "Đoàn Thanh niên Cộng sản Hồ Chí Minh được thành lập tại địa điểm nào?", options: ["Hà Nội","Sài Gòn","Hội An, Quảng Nam","Huế"], correct: 2 },
  { text: "Tên gọi đầu tiên của Đoàn khi thành lập năm 1930 là gì?", options: ["Đoàn Thanh niên Dân chủ Đông Dương","Đoàn Thanh niên Cộng sản Đông Dương","Hội Liên hiệp Thanh niên Việt Nam","Đoàn Thanh niên Phản đế Đông Dương"], correct: 1 },
  { text: "Tổ chức nào đã sáng lập ra Đoàn Thanh niên Cộng sản Hồ Chí Minh?", options: ["Chủ tịch Hồ Chí Minh trực tiếp sáng lập","Quốc tế Cộng sản","Đảng Cộng sản Việt Nam","Hội Thanh niên Cách mạng Đồng chí"], correct: 2 },
  { text: "Đại hội Đoàn toàn quốc lần thứ mấy quyết định lấy tên Đoàn TNCS Hồ Chí Minh?", options: ["Đại hội lần II","Đại hội lần III","Đại hội lần IV","Đại hội lần V"], correct: 1 },
  { text: "Ngày 26/3 hàng năm là ngày gì?", options: ["Ngày thành lập Đảng CSVN","Ngày Quốc tế Lao động","Ngày thành lập Đoàn TNCS HCM","Ngày Quốc tế Phụ nữ"], correct: 2 },
  { text: "Cờ Đoàn TNCS Hồ Chí Minh có màu sắc như thế nào?", options: ["Nền vàng, sao đỏ","Nền xanh, sao vàng","Nền đỏ, sao vàng 5 cánh, phù hiệu Đoàn","Nền đỏ, búa liềm vàng"], correct: 2 },
  { text: "Khẩu hiệu hành động nổi tiếng nhất của Đoàn Thanh niên là gì?", options: ["Thanh niên xung phong","Đâu cần thanh niên có, đâu khó có thanh niên","Tuổi trẻ sẵn sàng","Xung kích, tình nguyện, sáng tạo, phát triển"], correct: 1 },
  { text: "Tuổi đoàn viên theo Điều lệ Đoàn hiện hành là từ bao nhiêu tuổi đến bao nhiêu tuổi?", options: ["Từ 15 đến 30 tuổi","Từ 16 đến 30 tuổi","Từ 15 đến 35 tuổi","Từ 16 đến 35 tuổi"], correct: 1 },
  { text: "Lý Tự Trọng là chiến sĩ cách mạng trẻ tuổi nổi tiếng với câu nói nào?", options: ['"Tuổi trẻ là mùa xuân của đất nước"','"Con đường của thanh niên chỉ có thể là con đường cách mạng"','"Không có gì quý hơn độc lập tự do"','"Đâu cần thanh niên có"'], correct: 1 },
  { text: "Phong trào 'Ba sẵn sàng' của thanh niên miền Bắc thời chống Mỹ có nội dung là gì?", options: ["Sẵn sàng chiến đấu, sẵn sàng hy sinh, sẵn sàng phục vụ","Sẵn sàng nhập ngũ, sẵn sàng vào chiến trường miền Nam, sẵn sàng làm bất cứ việc gì Tổ quốc cần","Sẵn sàng lao động, sẵn sàng học tập, sẵn sàng chiến đấu","Sẵn sàng đi bất cứ đâu, sẵn sàng làm bất cứ việc gì, sẵn sàng hy sinh"], correct: 1 },
  { text: "Phong trào 'Ba đảm đang' là phong trào của tầng lớp nào?", options: ["Thanh niên nam toàn miền Bắc","Thanh niên nông thôn","Phụ nữ thanh niên miền Bắc thời chống Mỹ","Công nhân viên chức"], correct: 2 },
  { text: "Tháng Thanh niên được tổ chức vào tháng mấy hàng năm?", options: ["Tháng 1","Tháng 2","Tháng 3","Tháng 4"], correct: 2 },
  { text: "Đại hội Đoàn toàn quốc được tổ chức mấy năm một lần?", options: ["3 năm","4 năm","5 năm","6 năm"], correct: 2 },
  { text: "Cơ quan lãnh đạo cao nhất của Đoàn giữa hai kỳ đại hội là gì?", options: ["Ban Thường vụ Trung ương Đoàn","Ban Bí thư Trung ương Đoàn","Ban Chấp hành Trung ương Đoàn","Đại hội Đoàn toàn quốc"], correct: 2 },
  { text: "Nguyên tắc tổ chức và hoạt động cơ bản của Đoàn là gì?", options: ["Tập trung dân chủ","Tự do dân chủ","Tập thể lãnh đạo cá nhân phụ trách","Tập trung dân chủ và tập thể lãnh đạo cá nhân phụ trách"], correct: 3 },
  { text: "Chi đoàn là gì trong hệ thống tổ chức của Đoàn?", options: ["Cơ quan lãnh đạo cấp cao nhất","Tế bào cơ sở của Đoàn","Đơn vị hành chính của Đoàn","Ban chuyên trách của Đoàn"], correct: 1 },
  { text: "Đoàn viên được kết nạp vào Đoàn phải có độ tuổi tối thiểu là bao nhiêu?", options: ["15 tuổi","16 tuổi","17 tuổi","18 tuổi"], correct: 1 },
  { text: "Hội Liên hiệp Thanh niên Việt Nam được thành lập ngày tháng năm nào?", options: ["26/3/1930","15/10/1956","19/5/1941","02/9/1945"], correct: 1 },
  { text: "Đội Thiếu niên Tiền phong Hồ Chí Minh được thành lập ngày tháng năm nào?", options: ["26/3/1931","15/5/1941","01/6/1941","19/5/1941"], correct: 1 },
  { text: "Đoàn viên Đoàn TNCS HCM khi đủ điều kiện được Đoàn giới thiệu vào tổ chức nào?", options: ["Hội Liên hiệp Thanh niên Việt Nam","Hội Sinh viên Việt Nam","Đảng Cộng sản Việt Nam","Mặt trận Tổ quốc Việt Nam"], correct: 2 },
  { text: "Tuổi đội viên Đội Thiếu niên Tiền phong Hồ Chí Minh là từ bao nhiêu đến bao nhiêu tuổi?", options: ["6 đến 14 tuổi","9 đến 14 tuổi","9 đến 15 tuổi","6 đến 15 tuổi"], correct: 2 },
  { text: "Khăn quàng đỏ là biểu tượng của tổ chức nào?", options: ["Hội Sinh viên Việt Nam","Đoàn TNCS Hồ Chí Minh","Đội Thiếu niên Tiền phong Hồ Chí Minh","Hội Liên hiệp Thanh niên Việt Nam"], correct: 2 },
  { text: "Hội đồng Đội Trung ương trực thuộc tổ chức nào?", options: ["Bộ Giáo dục và Đào tạo","Trung ương Đoàn TNCS Hồ Chí Minh","Ủy ban Quốc gia về Thanh niên Việt Nam","Chính phủ nước CHXHCN Việt Nam"], correct: 1 },
  { text: "Bí thư thứ nhất Trung ương Đoàn nhiệm kỳ XII (2017-2022) là ai?", options: ["Nguyễn Anh Tuấn","Lê Quốc Phong","Bùi Quang Huy","Nguyễn Tấn Tuân"], correct: 1 },
  { text: "Bí thư thứ nhất Trung ương Đoàn hiện nay (nhiệm kỳ XIII, 2022-2027) là ai?", options: ["Nguyễn Anh Tuấn","Lê Quốc Phong","Bùi Quang Huy","Nguyễn Minh Triết"], correct: 2 },
  { text: "Kim Đồng - Đội trưởng đầu tiên của Đội Thiếu niên Tiền phong tên thật là gì?", options: ["Nguyễn Văn Kim","Nông Văn Dền","Lê Văn Đồng","Trần Kim Đồng"], correct: 1 },
  { text: "Giải thưởng cao nhất của Đoàn dành cho thanh niên có thành tích xuất sắc là gì?", options: ["Giải thưởng Hồ Chí Minh","Giải thưởng Lý Tự Trọng","Giải thưởng Nguyễn Du","Giải thưởng Nguyễn Văn Trỗi"], correct: 1 },
  { text: "Giải thưởng 'Sao Tháng Giêng' dành cho đối tượng nào?", options: ["Học sinh THPT xuất sắc","Sinh viên tiêu biểu","Đoàn viên thanh niên lao động xuất sắc","Thanh niên nông thôn tiêu biểu"], correct: 1 },
  { text: "Ngày truyền thống của lực lượng Thanh niên xung phong Việt Nam là ngày nào?", options: ["15/7","26/3","19/5","02/9"], correct: 0 },
  { text: "Phong trào 'Tuổi trẻ sáng tạo' nhằm khuyến khích thanh niên điều gì?", options: ["Học tập văn hóa","Nghiên cứu khoa học và sáng tạo kỹ thuật","Tham gia thể thao","Hoạt động văn nghệ"], correct: 1 },

  // === TƯ TƯỞNG HỒ CHÍ MINH (31-60) ===
  { text: "Bác Hồ đã khẳng định vai trò của thanh niên qua câu nói nổi tiếng nào?", options: ['"Thanh niên là rường cột của nước nhà"','"Thanh niên là người chủ tương lai của nước nhà"','"Tuổi trẻ là mùa xuân của đất nước"','"Thanh niên là lực lượng nòng cốt của cách mạng"'], correct: 1 },
  { text: "Bác Hồ sinh ngày tháng năm nào?", options: ["19/5/1890","19/5/1891","19/5/1892","19/5/1893"], correct: 0 },
  { text: "Bác Hồ đọc Tuyên ngôn Độc lập tại đâu vào ngày 02/9/1945?", options: ["Hội trường Ba Đình Hà Nội","Quảng trường Ba Đình Hà Nội","Nhà hát lớn Hà Nội","Phủ Chủ tịch Hà Nội"], correct: 1 },
  { text: "Bác Hồ mất ngày tháng năm nào?", options: ["02/9/1969","19/5/1969","03/9/1969","30/4/1969"], correct: 0 },
  { text: "Câu nói 'Không có gì quý hơn độc lập, tự do' là của ai?", options: ["Lê Duẩn","Võ Nguyên Giáp","Hồ Chí Minh","Trường Chinh"], correct: 2 },
  { text: "Tư tưởng Hồ Chí Minh về đạo đức cách mạng đề cao những phẩm chất nào trước tiên?", options: ["Dũng cảm, kiên cường","Cần, kiệm, liêm, chính, chí công vô tư","Đoàn kết, thống nhất","Trung thành, hy sinh"], correct: 1 },
  { text: "Chỉ thị 05-CT/TW của Bộ Chính trị về học tập và làm theo tư tưởng HCM được ban hành năm nào?", options: ["2014","2016","2018","2020"], correct: 1 },
  { text: "Theo Bác Hồ, 'Đoàn kết, đoàn kết, đại đoàn kết. Thành công, thành công, đại thành công' thể hiện điều gì?", options: ["Tầm quan trọng của lao động","Tầm quan trọng của đoàn kết dân tộc","Tầm quan trọng của học tập","Tầm quan trọng của đấu tranh cách mạng"], correct: 1 },
  { text: "Bác Hồ căn dặn trong Di chúc về việc 'bồi dưỡng thế hệ cách mạng cho đời sau' có nghĩa là gì?", options: ["Đào tạo cán bộ lãnh đạo","Chăm lo phát triển thế hệ trẻ","Xây dựng Đảng vững mạnh","Phát triển kinh tế đất nước"], correct: 1 },
  { text: "Bác Hồ ra đi tìm đường cứu nước từ cảng nào?", options: ["Cảng Hải Phòng","Cảng Đà Nẵng","Cảng Nhà Rồng (Sài Gòn)","Cảng Quy Nhơn"], correct: 2 },
  { text: "Bác Hồ ra đi tìm đường cứu nước vào năm nào?", options: ["1910","1911","1912","1913"], correct: 1 },
  { text: "Tên khai sinh của Chủ tịch Hồ Chí Minh là gì?", options: ["Nguyễn Tất Thành","Nguyễn Ái Quốc","Nguyễn Sinh Cung","Lý Thụy"], correct: 2 },
  { text: "Bác Hồ sáng lập ra Đảng Cộng sản Việt Nam vào năm nào?", options: ["1929","1930","1931","1932"], correct: 1 },
  { text: "Quê hương của Bác Hồ ở tỉnh nào?", options: ["Hà Tĩnh","Nghệ An","Thanh Hóa","Quảng Bình"], correct: 1 },
  { text: "Tác phẩm 'Đường Kách Mệnh' của Bác Hồ ra đời năm nào?", options: ["1925","1926","1927","1928"], correct: 2 },
  { text: "Bác Hồ thành lập tổ chức nào để đào tạo cán bộ tại Quảng Châu (Trung Quốc)?", options: ["Hội Việt Nam Cách mạng Thanh niên","Đảng Cộng sản Đông Dương","Mặt trận Việt Minh","Liên đoàn Các dân tộc bị áp bức ở Á Đông"], correct: 0 },
  { text: "Chiến dịch lịch sử mang tên Bác Hồ giải phóng Sài Gòn năm 1975 có tên là gì?", options: ["Chiến dịch Điện Biên Phủ","Chiến dịch Mùa Xuân 1975","Chiến dịch Hồ Chí Minh","Chiến dịch Tổng tiến công 1975"], correct: 2 },
  { text: "Bác Hồ trở về nước trực tiếp lãnh đạo cách mạng Việt Nam vào năm nào?", options: ["1940","1941","1942","1943"], correct: 1 },
  { text: "Báo 'Người Cùng Khổ' (Le Paria) do Bác Hồ sáng lập tại nước nào?", options: ["Liên Xô","Trung Quốc","Pháp","Anh"], correct: 2 },
  { text: "Nghị quyết Trung ương 4 (khóa XII) của Đảng tập trung vào nội dung gì?", options: ["Phát triển kinh tế","Tăng cường xây dựng chỉnh đốn Đảng ngăn chặn đẩy lùi suy thoái","Cải cách giáo dục","Bảo vệ môi trường"], correct: 1 },
  { text: "Nghị quyết 25-NQ/TW của BCH Trung ương Đảng (khóa X) về công tác thanh niên được ban hành năm nào?", options: ["2006","2007","2008","2009"], correct: 1 },
  { text: "Luật Thanh niên 2020 quy định thanh niên là người có độ tuổi từ đủ bao nhiêu đến bao nhiêu tuổi?", options: ["15 đến 30 tuổi","16 đến 30 tuổi","16 đến 35 tuổi","18 đến 30 tuổi"], correct: 1 },
  { text: "Ủy ban Quốc gia về Thanh niên Việt Nam do ai làm Chủ tịch?", options: ["Bí thư thứ nhất Trung ương Đoàn","Bộ trưởng Bộ Nội vụ","Phó Thủ tướng Chính phủ","Chủ tịch Mặt trận Tổ quốc"], correct: 2 },
  { text: "Chương trình 'Mùa hè xanh' do tổ chức nào phát động?", options: ["Bộ Giáo dục và Đào tạo","Đoàn Thanh niên","Hội Sinh viên","Ủy ban Nhân dân các tỉnh"], correct: 1 },
  { text: "Phong trào 'Thanh niên tình nguyện' được phát động chính thức từ năm nào?", options: ["1994","1996","1998","2000"], correct: 2 },
  { text: "Cuộc vận động 'Tuổi trẻ Việt Nam học tập và làm theo lời Bác' nhằm mục đích gì?", options: ["Nâng cao trình độ học vấn","Học tập và làm theo tư tưởng đạo đức phong cách Hồ Chí Minh","Phát triển kinh tế","Xây dựng tổ chức Đoàn vững mạnh"], correct: 1 },
  { text: "Chiến dịch Thanh niên tình nguyện hè được tổ chức thường niên từ năm nào?", options: ["1994","2000","2003","2005"], correct: 0 },
  { text: "Phong trào '5 xung kích phát triển kinh tế - xã hội và bảo vệ Tổ quốc' gồm các nội dung nào?", options: ["Xung kích phát triển kinh tế, sáng tạo khởi nghiệp, nâng cao văn hóa, bảo vệ Tổ quốc, xây dựng Đoàn","Phát triển kinh tế, tình nguyện, sáng tạo, bảo vệ Tổ quốc, xây dựng Đảng","Lao động sáng tạo, học tập rèn luyện, vì cộng đồng, bảo vệ Tổ quốc, hội nhập quốc tế","Tất cả các đáp án trên"], correct: 0 },
  { text: "Hội nghị lần thứ 8 BCH Trung ương Đảng (khóa XI) về phát triển bền vững biển Việt Nam đến năm nào?", options: ["2025","2030","2035","2045"], correct: 1 },
  { text: "Nghị quyết Đại hội Đảng lần thứ XIII đề ra mục tiêu đến năm 2030 Việt Nam trở thành nước như thế nào?", options: ["Nước phát triển thu nhập cao","Nước công nghiệp hiện đại","Nước đang phát triển có công nghiệp hiện đại thu nhập trung bình cao","Nước có nền kinh tế thị trường đầy đủ"], correct: 2 },

  // === KIẾN THỨC PHÁP LUẬT (61-90) ===
  { text: "Theo Bộ luật Hình sự, người đủ bao nhiêu tuổi trở lên phải chịu trách nhiệm hình sự về mọi tội phạm?", options: ["14 tuổi","16 tuổi","18 tuổi","20 tuổi"], correct: 2 },
  { text: "Độ tuổi đủ điều kiện đăng ký kết hôn theo Luật Hôn nhân và Gia đình hiện hành là bao nhiêu?", options: ["Nam từ 18, nữ từ 16","Nam từ 20, nữ từ 18","Nam từ 18, nữ từ 18","Nam từ 20, nữ từ 20"], correct: 1 },
  { text: "Tuổi bầu cử theo Hiến pháp Việt Nam năm 2013 là bao nhiêu tuổi trở lên?", options: ["16 tuổi","17 tuổi","18 tuổi","20 tuổi"], correct: 2 },
  { text: "Theo Luật Nghĩa vụ quân sự, công dân nam đủ bao nhiêu tuổi trong năm phải đăng ký nghĩa vụ quân sự?", options: ["16 tuổi","17 tuổi","18 tuổi","20 tuổi"], correct: 1 },
  { text: "Thời hạn phục vụ tại ngũ của hạ sĩ quan và binh sĩ theo Luật Nghĩa vụ quân sự là bao lâu?", options: ["18 tháng","24 tháng","30 tháng","36 tháng"], correct: 1 },
  { text: "Hành vi nào sau đây là vi phạm pháp luật về an toàn giao thông đường bộ?", options: ["Đi xe máy phân khối nhỏ không cần bằng lái","Dùng điện thoại khi đang điều khiển xe máy","Đi xe đạp ban đêm","Không mang theo giấy tờ xe"], correct: 1 },
  { text: "Độ tuổi tối thiểu được mua rượu, bia theo Luật Phòng chống tác hại rượu bia là bao nhiêu?", options: ["16 tuổi","17 tuổi","18 tuổi","20 tuổi"], correct: 2 },
  { text: "Hành vi tàng trữ, vận chuyển, mua bán trái phép chất ma túy bị xử lý như thế nào?", options: ["Xử phạt hành chính","Cảnh cáo","Truy cứu trách nhiệm hình sự","Giáo dục tại địa phương"], correct: 2 },
  { text: "Ngày truyền thống của Quân đội nhân dân Việt Nam là ngày nào?", options: ["22/12","30/4","19/8","02/9"], correct: 0 },
  { text: "Chiến thắng lịch sử Điện Biên Phủ diễn ra năm nào?", options: ["1950","1952","1954","1956"], correct: 2 },
  { text: "Ngày 30/4/1975 là ngày gì trong lịch sử Việt Nam?", options: ["Ngày ký Hiệp định Paris","Ngày giải phóng miền Nam thống nhất đất nước","Ngày thành lập nước CHXHCN Việt Nam","Ngày Cách mạng tháng Tám thành công"], correct: 1 },
  { text: "Hiến pháp nước CHXHCN Việt Nam hiện hành được thông qua vào năm nào?", options: ["1992","2001","2013","2015"], correct: 2 },
  { text: "Việt Nam có bao nhiêu tỉnh, thành phố trực thuộc Trung ương?", options: ["58","61","63","65"], correct: 2 },
  { text: "Quốc hội Việt Nam họp thường kỳ mấy kỳ một năm?", options: ["1 kỳ","2 kỳ","3 kỳ","4 kỳ"], correct: 1 },
  { text: "Nhiệm kỳ của Quốc hội Việt Nam là bao nhiêu năm?", options: ["4 năm","5 năm","6 năm","3 năm"], correct: 1 },
  { text: "Cơ quan nào có quyền ban hành Hiến pháp và Luật ở Việt Nam?", options: ["Chính phủ","Chủ tịch nước","Quốc hội","Tòa án nhân dân tối cao"], correct: 2 },
  { text: "Theo Hiến pháp 2013, Nhà nước Việt Nam là Nhà nước như thế nào?", options: ["Nhà nước pháp quyền xã hội chủ nghĩa của nhân dân do nhân dân vì nhân dân","Nhà nước cộng hòa","Nhà nước liên bang","Nhà nước quân chủ lập hiến"], correct: 0 },
  { text: "Văn phòng Chính phủ Việt Nam hiện đặt tại đâu?", options: ["Phủ Chủ tịch","Tòa nhà Quốc hội","Số 1 Hoàng Hoa Thám Hà Nội","Số 1 Hoàng Văn Thụ Hà Nội"], correct: 2 },
  { text: "Ngày Pháp luật Việt Nam được tổ chức vào ngày nào hàng năm?", options: ["9/11","10/12","19/8","02/9"], correct: 0 },
  { text: "Theo pháp luật Việt Nam, hành vi đánh bạc sẽ bị xử lý như thế nào?", options: ["Chỉ xử phạt hành chính","Có thể bị truy cứu trách nhiệm hình sự","Chỉ bị nhắc nhở","Không bị xử lý nếu thua ít tiền"], correct: 1 },
  { text: "Tội phạm về an ninh mạng theo Luật An ninh mạng 2018 bao gồm hành vi nào?", options: ["Tấn công mạng, phát tán phần mềm độc hại","Sử dụng không gian mạng chống Nhà nước","Tung tin giả gây hoang mang dư luận","Tất cả các hành vi trên"], correct: 3 },
  { text: "Luật An ninh mạng Việt Nam có hiệu lực từ ngày nào?", options: ["01/01/2018","01/6/2018","01/01/2019","01/6/2019"], correct: 2 },
  { text: "Hành vi nào sau đây vi phạm quy định về bảo vệ bí mật Nhà nước?", options: ["Đọc tin tức chính thống","Tiết lộ thông tin mật cho người không có thẩm quyền","Đăng ký tham quan các di tích lịch sử","Chụp ảnh phong cảnh đẹp"], correct: 1 },
  { text: "Theo Luật Thanh niên 2020, Nhà nước có trách nhiệm gì với thanh niên?", options: ["Tạo điều kiện học tập","Hỗ trợ việc làm khởi nghiệp","Chăm lo sức khỏe","Tất cả các đáp án trên"], correct: 3 },
  { text: "Phòng chống tham nhũng là trách nhiệm của ai?", options: ["Chỉ cơ quan Nhà nước","Chỉ Đảng viên","Toàn thể cán bộ đảng viên và nhân dân","Chỉ cơ quan thanh tra kiểm tra"], correct: 2 },
  { text: "Luật Phòng chống ma túy quy định hành vi nào là vi phạm pháp luật?", options: ["Tuyên truyền về tác hại của ma túy","Sử dụng ma túy dù chỉ một lần","Hỗ trợ cai nghiện ma túy","Báo cáo người sử dụng ma túy cho cơ quan chức năng"], correct: 1 },
  { text: "Hành vi bạo lực học đường bị xử lý theo quy định nào?", options: ["Chỉ xử lý kỷ luật trong nhà trường","Có thể bị xử lý hành chính hoặc hình sự tùy mức độ","Chỉ giáo dục nhắc nhở","Không có chế tài xử lý"], correct: 1 },
  { text: "Quyền bầu cử và ứng cử là quyền gì của công dân?", options: ["Quyền dân sự","Quyền chính trị cơ bản","Quyền kinh tế","Quyền văn hóa xã hội"], correct: 1 },
  { text: "Hành vi vi phạm trật tự công cộng có thể bị xử phạt như thế nào?", options: ["Chỉ bị nhắc nhở","Bị xử phạt vi phạm hành chính","Bị truy cứu trách nhiệm hình sự","Cả B và C tùy mức độ"], correct: 3 },
  { text: "Ngày Quốc tế Nhân quyền được tổ chức vào ngày nào?", options: ["10/11","10/12","01/12","15/11"], correct: 1 },

  // === KINH TẾ - XÃ HỘI - ĐẤT NƯỚC (91-120) ===
  { text: "Việt Nam đặt mục tiêu đến năm 2045 trở thành nước như thế nào?", options: ["Nước công nghiệp phát triển","Nước phát triển có thu nhập cao","Nước đứng top 20 kinh tế thế giới","Nước đạt mức sống trung bình châu Á"], correct: 1 },
  { text: "Ba trụ cột của chuyển đổi số quốc gia Việt Nam là gì?", options: ["Chính phủ số, Kinh tế số, Xã hội số","Công nghệ số, Dữ liệu số, Hạ tầng số","Giáo dục số, Y tế số, Giao thông số","Nông nghiệp số, Công nghiệp số, Dịch vụ số"], correct: 0 },
  { text: "Việt Nam là thành viên của tổ chức khu vực nào?", options: ["ASEAN","APEC","WTO","Tất cả đáp án trên"], correct: 3 },
  { text: "Quốc kỳ Việt Nam có màu gì?", options: ["Nền đỏ ngôi sao vàng năm cánh","Nền vàng ngôi sao đỏ năm cánh","Nền xanh ngôi sao vàng năm cánh","Nền trắng ngôi sao đỏ năm cánh"], correct: 0 },
  { text: "Quốc ca Việt Nam (Tiến quân ca) do ai sáng tác?", options: ["Phạm Duy","Văn Cao","Đỗ Nhuận","Hoàng Việt"], correct: 1 },
  { text: "Thủ đô của nước Cộng hòa Xã hội Chủ nghĩa Việt Nam là thành phố nào?", options: ["TP. Hồ Chí Minh","Đà Nẵng","Hà Nội","Huế"], correct: 2 },
  { text: "Việt Nam gia nhập ASEAN vào năm nào?", options: ["1993","1994","1995","1996"], correct: 2 },
  { text: "Hiệp định thương mại tự do EVFTA giữa Việt Nam và EU có hiệu lực từ năm nào?", options: ["2018","2019","2020","2021"], correct: 2 },
  { text: "Cuộc Cách mạng công nghiệp 4.0 tập trung vào những công nghệ nào?", options: ["Trí tuệ nhân tạo, IoT, Dữ liệu lớn, Điện toán đám mây","Điện và cơ khí hóa","Công nghệ thông tin và truyền thông","Năng lượng hạt nhân và vũ trụ"], correct: 0 },
  { text: "Chiến lược phát triển kinh tế - xã hội 2021-2030 của Việt Nam đặt mục tiêu tăng trưởng GDP bình quân là bao nhiêu?", options: ["6,0-6,5%/năm","6,5-7,0%/năm","7,0-7,5%/năm","7,5-8,0%/năm"], correct: 1 },
  { text: "Ngày Môi trường Thế giới được tổ chức vào ngày nào?", options: ["05/5","05/6","15/6","22/4"], correct: 1 },
  { text: "Biển Đông tiếng Anh được gọi là gì?", options: ["East Sea","South China Sea","East China Sea","Pacific Sea"], correct: 1 },
  { text: "Việt Nam có bao nhiêu di sản văn hóa và thiên nhiên được UNESCO công nhận tính đến năm 2023?", options: ["8 di sản","10 di sản","12 di sản","14 di sản"], correct: 0 },
  { text: "Vịnh Hạ Long được UNESCO công nhận là Di sản thiên nhiên thế giới lần đầu vào năm nào?", options: ["1993","1994","1995","1996"], correct: 1 },
  { text: "Kỳ quan thiên nhiên thế giới mới nào của Việt Nam được công nhận năm 2011?", options: ["Vịnh Hạ Long","Hang Sơn Đoòng","Ruộng bậc thang Mù Cang Chải","Vịnh Lan Hạ"], correct: 1 },
  { text: "Trung tâm kinh tế lớn nhất cả nước là thành phố nào?", options: ["Hà Nội","Đà Nẵng","TP. Hồ Chí Minh","Bình Dương"], correct: 2 },
  { text: "Cảng hàng không quốc tế lớn nhất Việt Nam hiện nay là cảng nào?", options: ["Sân bay Nội Bài","Sân bay Tân Sơn Nhất","Sân bay Đà Nẵng","Sân bay Long Thành"], correct: 1 },
  { text: "Chương trình mục tiêu quốc gia xây dựng nông thôn mới hướng đến mục tiêu nào?", options: ["Phát triển hạ tầng giao thông","Nâng cao đời sống nông dân","Xây dựng nông thôn mới văn minh hiện đại","Tất cả các đáp án trên"], correct: 3 },
  { text: "Việt Nam tham gia Công ước Liên hợp quốc về Luật Biển (UNCLOS) năm nào?", options: ["1982","1994","1995","1996"], correct: 1 },
  { text: "Diện tích lãnh thổ đất liền của Việt Nam khoảng bao nhiêu km²?", options: ["Khoảng 310.000 km²","Khoảng 330.000 km²","Khoảng 331.000 km²","Khoảng 350.000 km²"], correct: 2 },
  { text: "Dân số Việt Nam hiện nay (2023-2024) khoảng bao nhiêu người?", options: ["85 triệu","90 triệu","97-100 triệu","105 triệu"], correct: 2 },
  { text: "Việt Nam có bao nhiêu dân tộc anh em?", options: ["52 dân tộc","54 dân tộc","56 dân tộc","58 dân tộc"], correct: 1 },
  { text: "Con sông dài nhất Việt Nam là sông nào?", options: ["Sông Hồng","Sông Đồng Nai","Sông Mê Kông (phần ở Việt Nam là sông Cửu Long)","Sông Đà"], correct: 2 },
  { text: "Núi cao nhất Việt Nam là ngọn núi nào?", options: ["Núi Bạch Mã","Núi Ngọc Linh","Núi Fansipan","Núi Pu Si Lung"], correct: 2 },
  { text: "Chương trình OCOP (One Commune One Product) nhằm mục tiêu gì?", options: ["Phát triển sản phẩm đặc trưng của mỗi địa phương","Xây dựng thương hiệu quốc gia","Phát triển du lịch","Xúc tiến xuất khẩu"], correct: 0 },
  { text: "Đồng tiền của Việt Nam là gì?", options: ["Đô la Việt Nam","Đồng Việt Nam (VND)","Nhân dân tệ","Baht Việt Nam"], correct: 1 },
  { text: "Ngân hàng Nhà nước Việt Nam có chức năng gì?", options: ["Kinh doanh ngân hàng","Quản lý chính sách tiền tệ quốc gia","Cho vay doanh nghiệp","Quản lý chứng khoán"], correct: 1 },
  { text: "Mục tiêu 'Phát triển bền vững' (SDGs) của Liên hợp quốc có bao nhiêu mục tiêu?", options: ["15 mục tiêu","17 mục tiêu","19 mục tiêu","21 mục tiêu"], correct: 1 },
  { text: "Ngày Quốc tế Phòng chống tham nhũng là ngày nào?", options: ["09/12","10/12","11/12","12/12"], correct: 0 },
  { text: "Đề án phát triển thanh niên giai đoạn 2021-2030 được Thủ tướng Chính phủ ban hành theo Quyết định nào?", options: ["1331/QĐ-TTg","1453/QĐ-TTg","1562/QĐ-TTg","1178/QĐ-TTg"], correct: 0 },

  // === VĂN HÓA - XÃ HỘI - ĐẠO ĐỨC (121-150) ===
  { text: "Phong trào 'Toàn dân đoàn kết xây dựng đời sống văn hóa' do tổ chức nào chủ trì?", options: ["Bộ Văn hóa Thể thao và Du lịch","Mặt trận Tổ quốc Việt Nam","Đoàn Thanh niên","Ủy ban Nhân dân các cấp"], correct: 1 },
  { text: "Văn hóa ứng xử trên mạng xã hội cần đảm bảo những nguyên tắc gì?", options: ["Chỉ đăng nội dung giải trí","Tôn trọng, trách nhiệm, an toàn, lành mạnh","Không đăng thông tin cá nhân","Chỉ chia sẻ từ nguồn chính thống"], correct: 1 },
  { text: "Hành vi nào sau đây là hành vi vi phạm đạo đức của người đoàn viên?", options: ["Tham gia hoạt động tình nguyện","Tung tin giả mạo trên mạng xã hội","Học tập nâng cao trình độ","Đóng góp ý kiến xây dựng tổ chức Đoàn"], correct: 1 },
  { text: "Giá trị cốt lõi của người đoàn viên thanh niên Việt Nam là gì?", options: ["Trí tuệ, năng động, sáng tạo, xung kích","Bản lĩnh, trí tuệ, đoàn kết, tiên phong","Đoàn kết, trách nhiệm, cống hiến, sáng tạo","Yêu nước, tự hào, đoàn kết, tình nguyện"], correct: 1 },
  { text: "Ngày Gia đình Việt Nam được tổ chức vào ngày nào hàng năm?", options: ["15/5","28/6","15/7","01/6"], correct: 1 },
  { text: "Tết Nguyên Đán là Tết truyền thống của dân tộc nào ở Việt Nam?", options: ["Chỉ người Kinh","Chỉ người Hoa","Nhiều dân tộc trong cộng đồng các dân tộc Việt Nam","Tất cả 54 dân tộc"], correct: 2 },
  { text: "Di sản phi vật thể của Việt Nam được UNESCO công nhận có bao nhiêu (tính đến 2023)?", options: ["10 di sản","13 di sản","15 di sản","17 di sản"], correct: 2 },
  { text: "Nhã nhạc cung đình Huế được UNESCO công nhận là di sản văn hóa phi vật thể vào năm nào?", options: ["2001","2003","2005","2007"], correct: 1 },
  { text: "Lễ hội Đền Hùng được tổ chức vào ngày nào âm lịch hàng năm?", options: ["Mùng 10 tháng 3","Mùng 5 tháng 5","Rằm tháng 7","Rằm tháng 8"], correct: 0 },
  { text: "Ngày Giỗ Tổ Hùng Vương là ngày lễ lớn được công nhận là ngày lễ quốc gia từ năm nào?", options: ["2005","2007","2009","2011"], correct: 2 },
  { text: "Ngày Quốc tế Phụ nữ là ngày nào?", options: ["08/3","20/10","01/5","15/5"], correct: 0 },
  { text: "Ngày Phụ nữ Việt Nam là ngày nào?", options: ["08/3","20/10","01/5","15/5"], correct: 1 },
  { text: "Đặc điểm của người Việt Nam trong văn hóa giao tiếp truyền thống là gì?", options: ["Trọng tình nghĩa, coi trọng cộng đồng gia đình làng xã","Đề cao cá nhân","Coi trọng vật chất hơn tinh thần","Ít giao tiếp với người ngoài"], correct: 0 },
  { text: "Phong trào 'Xây dựng trường học thân thiện học sinh tích cực' do cơ quan nào phát động?", options: ["Đoàn Thanh niên","Hội đồng Đội","Bộ Giáo dục và Đào tạo","Mặt trận Tổ quốc"], correct: 2 },
  { text: "Học sinh sinh viên vi phạm đạo đức như gian lận trong thi cử có thể bị xử lý như thế nào?", options: ["Chỉ nhắc nhở","Kỷ luật từ khiển trách đến đuổi học","Chỉ phạt tiền","Không có chế tài xử lý"], correct: 1 },
  { text: "Giải thưởng 'Nhân tài Đất Việt' được tổ chức nhằm mục đích gì?", options: ["Tôn vinh tài năng trẻ Việt Nam","Tuyển chọn nhân tài cho Nhà nước","Phát triển kinh tế","Bảo tồn văn hóa dân tộc"], correct: 0 },
  { text: "Ngày Thể thao Việt Nam được tổ chức vào ngày nào hàng năm?", options: ["27/3","01/5","02/9","15/10"], correct: 0 },
  { text: "SEA Games là đại hội thể thao của khu vực nào?", options: ["Đông Á","Đông Nam Á","Nam Á","Châu Á - Thái Bình Dương"], correct: 1 },
  { text: "Đại hội Thể thao Đông Nam Á SEA Games 31 được tổ chức tại đâu năm 2022?", options: ["Hà Nội, Việt Nam","Bangkok, Thái Lan","Manila, Philippines","Campuchia"], correct: 0 },
  { text: "Bộ Quy tắc ứng xử trên mạng xã hội được Bộ Thông tin và Truyền thông ban hành vào năm nào?", options: ["2019","2020","2021","2022"], correct: 1 },
  { text: "Thanh niên cần tránh những hành vi nào trên không gian mạng?", options: ["Đăng tin giả, bình luận tiêu cực, phát tán nội dung xấu độc","Chia sẻ bài viết của bạn bè","Tham gia diễn đàn thảo luận lành mạnh","Mua sắm trực tuyến ở địa chỉ uy tín"], correct: 0 },
  { text: "Ngày Nhà giáo Việt Nam là ngày nào?", options: ["20/10","20/11","01/12","15/12"], correct: 1 },
  { text: "Ngày Thầy thuốc Việt Nam là ngày nào?", options: ["20/2","27/2","08/3","15/3"], correct: 1 },
  { text: "Ngày Quốc tế Lao động là ngày nào?", options: ["01/4","01/5","01/6","01/7"], correct: 1 },
  { text: "Vật liệu nào sau đây được xếp vào loại rác thải nguy hại cần xử lý đặc biệt?", options: ["Vỏ lon đồ uống","Pin điện thoại","Giấy báo cũ","Vỏ chai nhựa"], correct: 1 },
  { text: "Tiêu chí 'Gia đình văn hóa' gồm nội dung cốt lõi nào?", options: ["Gia đình no ấm bình đẳng tiến bộ hạnh phúc","Gia đình gương mẫu chấp hành pháp luật","Gia đình tích cực tham gia phong trào thi đua","Tất cả các đáp án trên"], correct: 3 },
  { text: "Xây dựng lối sống 'Tự lực tự cường' có nghĩa là gì đối với thanh niên?", options: ["Không cần sự giúp đỡ của ai","Phát huy nội lực không ỷ lại dám nghĩ dám làm","Chỉ dựa vào bản thân mọi tình huống","Tránh xa mọi sự hỗ trợ của xã hội"], correct: 1 },
  { text: "Phong trào 'Hiến máu tình nguyện' mang ý nghĩa nhân văn gì?", options: ["Cứu sống người bệnh cần máu","Tuyên truyền về sức khỏe cộng đồng","Đoàn kết tương thân tương ái","Tất cả đáp án trên"], correct: 3 },
  { text: "Ngày Dân số Thế giới là ngày nào?", options: ["07/7","11/7","15/7","21/7"], correct: 1 },
  { text: "Chính sách dân số của Việt Nam hiện nay hướng đến mục tiêu gì?", options: ["Hạn chế sinh đẻ","Duy trì mức sinh thay thế và nâng cao chất lượng dân số","Khuyến khích sinh nhiều con","Không có chính sách cụ thể"], correct: 1 },
  { text: "Phong trào 'Mỗi ngày một việc tốt' dành cho ai?", options: ["Đoàn viên thanh niên","Đội viên thiếu niên","Học sinh sinh viên","Tất cả người dân"], correct: 1 },

  // === AN NINH - QUỐC PHÒNG - ĐỐI NGOẠI (151-175) ===
  { text: "Thanh niên có nghĩa vụ nào đối với sự nghiệp bảo vệ Tổ quốc?", options: ["Thực hiện nghĩa vụ quân sự","Tham gia xây dựng quốc phòng toàn dân","Học tập quốc phòng an ninh","Tất cả đáp án trên"], correct: 3 },
  { text: "Giáo dục quốc phòng và an ninh bắt buộc với đối tượng nào?", options: ["Chỉ học sinh THPT","Chỉ sinh viên đại học","Học sinh sinh viên từ THPT trở lên","Tất cả công dân trưởng thành"], correct: 2 },
  { text: "Lực lượng nào là nòng cốt của quốc phòng toàn dân ở Việt Nam?", options: ["Dân quân tự vệ","Quân đội nhân dân và Công an nhân dân","Công an nhân dân","Bộ đội biên phòng"], correct: 1 },
  { text: "Đường lối đối ngoại của Việt Nam được xác định là gì?", options: ["Độc lập tự chủ đa phương hóa đa dạng hóa","Chỉ ưu tiên quan hệ với các nước ASEAN","Ưu tiên quan hệ với các nước lớn","Trung lập trong mọi vấn đề quốc tế"], correct: 0 },
  { text: "Việt Nam đã ký Hiệp định Paris về chấm dứt chiến tranh lập lại hòa bình ở Việt Nam vào năm nào?", options: ["1972","1973","1974","1975"], correct: 1 },
  { text: "Tuyên bố về ứng xử của các bên ở Biển Đông (DOC) được ký kết năm nào?", options: ["2000","2002","2004","2006"], correct: 1 },
  { text: "Việt Nam gia nhập Liên Hợp Quốc vào năm nào?", options: ["1974","1975","1976","1977"], correct: 2 },
  { text: "Quan hệ đối tác chiến lược toàn diện là mức quan hệ cao nhất giữa Việt Nam và các nước. Tính đến 2023 Việt Nam có bao nhiêu đối tác loại này?", options: ["5 đối tác","6 đối tác","7 đối tác","8 đối tác"], correct: 1 },
  { text: "Việt Nam đảm nhận vai trò Ủy viên không thường trực Hội đồng Bảo an Liên Hợp Quốc nhiệm kỳ gần nhất vào năm nào?", options: ["2008-2009","2014-2015","2020-2021","2022-2023"], correct: 2 },
  { text: "ASEAN được thành lập năm nào và có bao nhiêu thành viên ban đầu?", options: ["1965, 4 nước","1967, 5 nước","1970, 6 nước","1975, 7 nước"], correct: 1 },
  { text: "ASEAN hiện có bao nhiêu quốc gia thành viên?", options: ["9 quốc gia","10 quốc gia","11 quốc gia","12 quốc gia"], correct: 1 },
  { text: "Trụ sở của ASEAN đặt tại thủ đô nào?", options: ["Kuala Lumpur Malaysia","Bangkok Thái Lan","Jakarta Indonesia","Manila Philippines"], correct: 2 },
  { text: "Việt Nam lần đầu tiên tổ chức APEC vào năm nào?", options: ["2003","2005","2006","2007"], correct: 3 },
  { text: "Biểu tượng hòa bình nổi tiếng thế giới là hình ảnh gì?", options: ["Bàn tay mở","Chim bồ câu trắng","Cờ trắng","Cành ô liu"], correct: 1 },
  { text: "Ngày Quốc tế Hòa bình là ngày nào?", options: ["21/9","01/10","10/11","25/12"], correct: 0 },
  { text: "Tổ chức nào sau đây là cơ quan chuyên trách về hòa bình và an ninh quốc tế?", options: ["WHO","UNESCO","Hội đồng Bảo an Liên Hợp Quốc","IMF"], correct: 2 },
  { text: "Chiến lược bảo vệ Tổ quốc trong tình hình mới nhấn mạnh kết hợp giữa hai nhiệm vụ nào?", options: ["Xây dựng kinh tế và bảo vệ Tổ quốc","Phát triển văn hóa và bảo vệ môi trường","Đào tạo nhân lực và phát triển công nghệ","Xây dựng Đảng và Nhà nước"], correct: 0 },
  { text: "Bộ Quốc phòng Việt Nam hiện có nhiệm vụ gì?", options: ["Quản lý quân đội","Bảo vệ an ninh quốc gia","Thực hiện quản lý nhà nước về quốc phòng","Tất cả các đáp án trên"], correct: 2 },
  { text: "Lực lượng Công an nhân dân Việt Nam trực thuộc cơ quan nào?", options: ["Quân ủy Trung ương","Bộ Quốc phòng","Bộ Công an dưới sự lãnh đạo của Đảng và Nhà nước","Ủy ban Thường vụ Quốc hội"], correct: 2 },
  { text: "Ngày truyền thống Công an nhân dân Việt Nam là ngày nào?", options: ["19/8","19/10","19/12","19/2"], correct: 1 },
  { text: "Phong trào 'Toàn dân bảo vệ an ninh Tổ quốc' có ý nghĩa gì?", options: ["Huy động toàn thể nhân dân tham gia đấu tranh phòng chống tội phạm và bảo vệ an ninh","Chỉ dành riêng cho lực lượng vũ trang","Tuyên truyền về pháp luật","Xây dựng hệ thống camera an ninh"], correct: 0 },
  { text: "Thanh niên tham gia bảo vệ chủ quyền biển đảo có thể thực hiện qua hoạt động nào?", options: ["Chỉ tham gia hải quân","Tuyên truyền nâng cao nhận thức cộng đồng","Tham gia dân quân tự vệ biển","Tất cả đáp án trên"], correct: 3 },
  { text: "Ngày Biên phòng toàn dân là ngày nào?", options: ["03/3","03/4","03/5","03/6"], correct: 0 },
  { text: "Bộ Công an Việt Nam thực hiện chiến lược chuyển đổi số theo định hướng nào?", options: ["Xây dựng Công an điện tử","Xây dựng Công an số","Xây dựng cơ sở dữ liệu quốc gia về dân cư","Cả B và C"], correct: 3 },
  { text: "Nghị quyết Trung ương 8 (khóa XI) về Chiến lược bảo vệ Tổ quốc trong tình hình mới được ban hành năm nào?", options: ["2012","2013","2014","2015"], correct: 1 },

  // === KHOA HỌC - CÔNG NGHỆ - GIÁO DỤC (176-200) ===
  { text: "Đề án 'Phát triển ứng dụng dữ liệu về dân cư định danh và xác thực điện tử phục vụ chuyển đổi số quốc gia' có tên gọi là gì?", options: ["Đề án 06","Đề án 844","Đề án 1831","Đề án 749"], correct: 0 },
  { text: "Chương trình 'Nghiên cứu khoa học và công nghệ' của thanh niên được Đoàn phát động nhằm mục đích gì?", options: ["Khuyến khích thanh niên học tập","Thúc đẩy nghiên cứu đổi mới sáng tạo","Xây dựng văn hóa đọc","Phát triển thể lực"], correct: 1 },
  { text: "Đoàn Thanh niên phát động chương trình 'Thắp sáng ước mơ thanh niên Việt Nam' nhằm mục đích gì?", options: ["Hỗ trợ học bổng cho học sinh","Khơi dậy khát vọng cống hiến và hoài bão của thanh niên","Phát triển kỹ năng mềm","Tạo việc làm cho thanh niên"], correct: 1 },
  { text: "Giải thưởng 'Khởi nghiệp sáng tạo Việt Nam' dành cho đối tượng nào?", options: ["Chỉ sinh viên đại học","Doanh nghiệp khởi nghiệp của thanh niên","Nhà khoa học trẻ","Tất cả công dân Việt Nam"], correct: 1 },
  { text: "Cuộc thi 'Trí tuệ Việt Nam' do tổ chức nào phát động?", options: ["Bộ Giáo dục và Đào tạo","Đoàn Thanh niên Cộng sản Hồ Chí Minh","Hội Sinh viên Việt Nam","Ủy ban Quốc gia về Thanh niên"], correct: 1 },
  { text: "Mục tiêu của chương trình 'Thanh niên khởi nghiệp' giai đoạn 2022-2027 là gì?", options: ["Hỗ trợ 100.000 thanh niên khởi nghiệp","Hỗ trợ ít nhất 40.000 thanh niên khởi nghiệp thành công","Xây dựng 1.000 startup","Phát triển hệ sinh thái khởi nghiệp"], correct: 1 },
  { text: "Chỉ số đổi mới sáng tạo toàn cầu (GII) đo lường điều gì?", options: ["GDP của các quốc gia","Năng lực đổi mới sáng tạo của các quốc gia","Trình độ giáo dục","Chỉ số hạnh phúc"], correct: 1 },
  { text: "Nền tảng số nào của Việt Nam được Đoàn Thanh niên giới thiệu để phục vụ học tập của thanh thiếu nhi?", options: ["VNeID","Thanh Nien App","nền tảng học trực tuyến của Bộ GD&ĐT","Tất cả đáp án trên"], correct: 3 },
  { text: "Phong trào 'Cán bộ Đoàn học tập lý luận chính trị' nhằm mục đích gì?", options: ["Nâng cao trình độ lý luận chính trị cho cán bộ Đoàn","Chuẩn bị nguồn nhân lực cho Đảng","Xây dựng tổ chức Đoàn vững mạnh","Cả A và B"], correct: 3 },
  { text: "Chương trình 'Đào tạo 1 triệu kỹ năng số cho thanh niên' của Đoàn hướng đến mục tiêu nào?", options: ["Phổ cập kỹ năng số cơ bản cho thanh niên Việt Nam","Đào tạo lập trình viên","Xây dựng nền kinh tế số","Phát triển AI Việt Nam"], correct: 0 },
  { text: "Ứng dụng VNeID là ứng dụng phục vụ mục đích gì?", options: ["Mua sắm trực tuyến","Định danh điện tử và cung cấp dịch vụ công trực tuyến","Học tập trực tuyến","Kết nối mạng xã hội"], correct: 1 },
  { text: "Mức tăng trưởng kinh tế của Việt Nam năm 2022 đạt khoảng bao nhiêu?", options: ["5,0%","6,5%","8,02%","9,5%"], correct: 2 },
  { text: "Việt Nam đặt mục tiêu đạt tỷ lệ người dùng internet đến năm 2025 là bao nhiêu?", options: ["70%","80%","85%","90%"], correct: 2 },
  { text: "Ngày Khoa học và Công nghệ Việt Nam là ngày nào?", options: ["18/5","19/5","20/5","21/5"], correct: 0 },
  { text: "Hội thi 'Tin học trẻ' được tổ chức nhằm mục đích gì?", options: ["Phát hiện và bồi dưỡng tài năng tin học trẻ","Phổ cập tin học cho mọi người","Thi lập trình quốc tế","Phát triển game Việt Nam"], correct: 0 },
  { text: "Chương trình 'Tôi yêu Tổ quốc tôi' của Đoàn Thanh niên nhằm mục tiêu gì?", options: ["Khơi dậy tình yêu nước và niềm tự hào dân tộc trong thanh niên","Phát triển du lịch nội địa","Bảo tồn di sản văn hóa","Tìm hiểu lịch sử"], correct: 0 },
  { text: "Cuộc thi 'Ý tưởng sáng tạo thanh niên' khuyến khích thanh niên điều gì?", options: ["Đề xuất giải pháp sáng tạo giải quyết vấn đề xã hội và phát triển đất nước","Tham gia nghiên cứu khoa học","Viết báo","Thi thể thao"], correct: 0 },
  { text: "Phong trào học sinh sinh viên với công nghệ thông tin nhằm mục tiêu gì?", options: ["Nâng cao kỹ năng ứng dụng CNTT","Phổ cập lập trình","Xây dựng ứng dụng cho cộng đồng","Tất cả đáp án trên"], correct: 3 },
  { text: "Nghị quyết 52-NQ/TW của Bộ Chính trị về chủ động tham gia cuộc Cách mạng công nghiệp lần thứ tư được ban hành năm nào?", options: ["2017","2018","2019","2020"], correct: 2 },
  { text: "Thanh niên có vai trò gì trong phát triển kinh tế số?", options: ["Lực lượng tiên phong ứng dụng và phát triển kinh tế số","Chỉ là người tiêu dùng số","Lực lượng hỗ trợ người cao tuổi dùng công nghệ","Không có vai trò cụ thể"], correct: 0 },
  { text: "Mạng 5G được Việt Nam thử nghiệm thương mại từ năm nào?", options: ["2019","2020","2021","2022"], correct: 0 },
  { text: "Chương trình chuyển đổi số quốc gia đến năm 2025 và định hướng đến năm 2030 được phê duyệt theo Quyết định số mấy của Thủ tướng?", options: ["749/QĐ-TTg","844/QĐ-TTg","1831/QĐ-TTg","06/QĐ-TTg"], correct: 0 },
  { text: "Việt Nam phấn đấu lọt top bao nhiêu quốc gia dẫn đầu về Chỉ số đổi mới sáng tạo (GII) trong ASEAN vào năm 2030?", options: ["Top 3","Top 4","Top 5","Top 6"], correct: 0 },
  { text: "Chương trình 'Đại sứ văn hóa đọc' do tổ chức nào phát động?", options: ["Bộ Văn hóa Thể thao và Du lịch","Đoàn TNCS Hồ Chí Minh","Bộ Giáo dục và Đào tạo","Hội Nhà văn Việt Nam"], correct: 1 },
  { text: "Thanh niên Việt Nam được khuyến khích tham gia vào lĩnh vực nào để phát triển đất nước trong thời đại 4.0?", options: ["Chỉ nông nghiệp truyền thống","Trí tuệ nhân tạo, dữ liệu lớn, điện toán đám mây, IoT","Chỉ sản xuất công nghiệp","Chỉ dịch vụ thương mại"], correct: 1 }
];
